---
title: "Methods for Research and Policy Evaluation"
toc: true
---

This website aims to support the class 'Methods for Research and Policy Evaluation', taught in the school of Public Affairs of Sciences Po. 

# Course description

The objective of this course is to introduce quantitative methods for causal inference, relying on mathematical formalization and applying them to concrete research situations. Students will learn how to handle data - assembling a dataset, cleaning it, and preparing it for quantitative analysis. The methods covered will include a review of linear models (simple and multiple regressions) and nonlinear models (probit, logit), before moving on to the core of the course: causal inference, namely DiD, RDD, and IV (2SLS, 2SRI). Each session will be divided equally between the presentation of methods and their mathematical formulation, and in-class exercisesdesigned to help students master the associated coding techniques. The final goal is to replicate a scientific article that applies one or more of these methods, enabling students to develop technical skills useful for research or for the quantitative evaluation of public policies. Another objective is to ncultivate critical thinking regarding the strengths and limitations of such research methods. It is therefore particularly well suited for students who wish to develop their skills in computer science, mathematics, and quantitative research methods.

# Sessions

| Session | Date      | Content |
|---------|-----------|---------|
| Session 1: Dataset Building and Descriptive Statistics | 26/01/26 | Students will learn how to build and prepare a dataset, including data cleaning (handling missing values, outliers, and duplicates). They will explore data visualization techniques (e.g., box plots) to identify patterns. Take-home assignment: create a dataset from a scientific article. |
| Session 2: OLS: Simple and Multiple Linear Regressions and Analysis | 09/02/26 | Covers ordinary least squares (OLS) regression, interpreting coefficients, statistical significance tests, R-squared and adjusted R-squared, and regression concerns (e.g., heteroskedasticity). Take-home: use Session 1 dataset to run regressions. |
| Session 3: Non-Linear Regressions and Analysis | 23/02/26 | Introduction to logit and probit models for binary and multinomial outcomes. Students learn coefficient interpretation, maximum likelihood estimation, and model fit evaluation. Take-home: run non-linear regressions on Session 1 dataset. |
| Session 4: Difference-in-Differences (DiD) | 09/03/26 | Explore Difference-in-Differences method, defining treatment/control groups, and testing parallel trend assumption. Includes de Chaisemartin & d’Haultfœuille framework. Take-home: apply DiD to Session 1 dataset. |
| Session 5: Regression Discontinuity Design (RDD) | 23/03/26 | Learn Regression Discontinuity Design (sharp and fuzzy), assumption testing, bandwidth selection, and interpreting treatment effects at the cutoff. Take-home: run sharp/fuzzy RDD on Session 1 dataset. |
| Session 6: Instrumental Variables (IV), Two-Stage Least Squares (2SLS) and Two-Stage Residual Inclusion (2SRI) | 13/04/26 | Explore IV methods, focusing on 2SLS and 2SRI to address endogeneity and unobserved confounding. Emphasis on instrument selection, estimation, and coefficient interpretation. Take-home: apply IV, 2SLS, and/or 2SRI to Session 1 dataset. |
: {tbl-colwidths="[30,10, 60]"}

# Course objectives

* Identify and apply quantitative methods central to the evaluation of public policies
* Understand and compare key methodologies used in quantitative research for public policy
evaluation
* Acquire practical research skills necessary for effective policy analysis and evaluation
* Develop programming skills for data management and analysis and research applications in
public policy

# Prerequisites

* Basic coding skills (beginners welcome) - Stata, R, or Python are all acceptable. Students
should know how to use an IDE of their choice, how to import data, and have some
introductory knowledge of a programming language.
* Basic statistical concepts - e.g. students should know what a mean, a median, a standard
deviation, a statistical sample and statistical inference are.

# Course validation 

The course will be evaluated using a simplified pass/fail system. Evaluation will be based on a short report (five pages) replicating a scientific article or a report that uses a causal inference method, provided by the lecturers at the beginning of the semester. The writing of this report will be supported incrementally throughout the semester, with guidance provided during each class, so that students can progress step by step in the making of the paper.

# Course format

The course is structured with a 1-hour lecture (CM) followed by a 1-hour practical session (TP). Students are required to have a computer with RStudio or Stata installed (Stata licenses are available through Sciences Po). Each session begins with an introduction to the methods to be used, during which their mathematical formalization is covered. The second part of the session focuses on applying these methods to real-world data using RStudio or Stata. Classes are held every two weeks for a total of 2 hours and are conducted in English.

# References

## Online resources

* De Chaisemartin, Clément &amp; d’Haultfœuille, Xavier. Credible Answers to Hard Questions:
DiD for Natural Experiments. SSRN. (2023)
* Cunningham, Scott. Causal Inference: The Mixtape. (2021) 
Available at: <https://mixtape.scunning.com/>. 
This resource provides an introduction to causal inference methods, aimed at
helping social scientists determine causal relationships. It includes modeling
techniques and coding instructions for both R and Stata.
* Huntington-Klein. The Effect: An Introduction to Research Design and Causality. (2021) Available at: <https://theeffectbook.net/>
This resource introduces students to research design and causality, particularly in
the context of observational data.

## Books

* Angrist, Joshua & Pischke, Jörn-Steffen. Mostly Harmless Econometrics: An Empiricist’s
Companion. 2009, Princeton University Press.
* Greene, William. Econometric Analysis - 8th ed. 2019. Pearson.
* Heiss, Florian. Using R for Introductory Econometrics - 2nd ed. 2020. Independently
Published.
* Hurlin, Christophe &amp; Mignon, Valérie. Statistique et probabilités en économie-gestion - 2e
ed. 2022, Dunod.
* Mignon, Valérie. Econométrie : Théorie et applications - 2e éd. 2022, Economica.
* Spiegelhalter, David. The Art of Statistics: Learning from Data. 2019, Pelican.
* Wooldridge, Jeffrey. Introductory Econometrics: A Modern Approach - 8th ed. 2025.
Cengage Learning.


## Videos

A selection of video resources relevant to the course

* Ben Lambert. Full Channel. YouTube. Available at: <www.youtube.com/@SpartacanUsuals> This YouTube channel offers detailed explanations of undergraduate and graduate econometrics courses, emphasizing intuition and examples over advanced mathematics.

* LISER. “DiD Training with Prof. de Chaisemartin.” YouTube. Available at:
<www.youtube.com/watch?v=d2T3QmGWOn0&amp;pp=ygURZGUgY2hhaXNlbWFydGluZSA%3D>. This YouTube series offers an in-depth course on DiD, reviewing fundamental concepts, progressing to advanced techniques, while highlighting the latest innovations driving the ongoing “DiD revolution.” The course is led by Prof. Clément de Chaisemartin.

* Taylor Wright. “Two-Way Fixed Effects Regressions with Several Treatments.” YouTube. Available at: <https://www.youtube.com/watch?v=UHeJoc27qEM> Prof. Clément de Chaisemartin presents his work with Prof. Xavier d’Haultfœuille. The paper shows that Two-Way Fixed Effects (TWFE) regressions are prone to bias from heterogeneous effects and contamination. The authors propose a robust DiD estimator with results differing from TWFE in their application.